"""empty message

Revision ID: 3c58166c2795
Revises: 45b4f70881ab
Create Date: 2019-11-25 22:27:09.114378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c58166c2795'
down_revision = '45b4f70881ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('salt', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', 'salt')
    # ### end Alembic commands ###
