"""empty message

Revision ID: 45b4f70881ab
Revises: ba15d1f7dee3
Create Date: 2019-11-25 22:18:35.977973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b4f70881ab'
down_revision = 'ba15d1f7dee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('_password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', '_password')
    # ### end Alembic commands ###
